간단한 계산기 앱 구현
ghojeong/dreamfora pull request #2
Opened 2021-09-02 01:04 UTC by ghojeong

@nathankim0 께서 지도해주신 대로, 간단한 계산기 앱을 구현해보았습니다.
앞오로도 C# 공부는 이론부터 공부하는게 아니라, 지금처럼 직접 코딩해보면서 진행하려 합니다.

업무 때문에 바쁘실 것 같아서, 리뷰해야할 코드량을 최대한 줄이려고 노력했습니다.
앞으로 같이 코드 리뷰 문화를 만들어나가고 싶어서,
코드 리뷰를 어떻게해야할지 이야기 나누는거 언제든 환영합니다.

### 개선이 필요한 내용

- Keypad 와 Operation 버튼들을 별도 모듈로 분리 필요
- Result 와 NumberBuffer 를 외부 서버에 상태가 있을 경우에 대한 비동기 구현 도전
- xaml 에서 Keypad 의 반복적인 숫자 컴포넌트 표현하기

2021-09-02 01:05 UTC, ghojeong commented
@jvhe 에게도 리뷰를 부탁드리려고 합니다.

2021-09-02 02:39 UTC, nathankim0 requested changes
오우 파이로! 첫 과제 수고하셨어요! ❤️

2021-09-02 02:39 UTC, nathankim0 commented on xamarin/Calculator/Calculator/MainPage.xaml.cs
> +            MultiplyButton = new Button() { Text = "*" };
저희는 C# 에서 렌더링을 하지 않고, xaml 으로 템플릿을 만드는 방법을 선호하고 있습니다.
xaml 으로 템플릿을 만들어 주시면 좋을것 같아요!

2021-09-02 02:39 UTC, nathankim0 commented on xamarin/Calculator/Calculator/MainPage.xaml.cs
> +        }
모듈화 어떻게 해야할지, 미팅잡고 같이 이야기해보죠!

아니면, 관련된 좋은 블로글 링크 같은거 첨부할수도 있음

2021-09-02 02:39 UTC, nathankim0 commented on xamarin/Calculator/Calculator/MainPage.xaml.cs
> +        // FIXME: Operation 버튼들을 별도의 클래스로 분리해서 모듈화하기
근데 생각해보니, 이거 굳이 시간들여서 고칠필요 없을것 같습니다.
FIXME 주석 지워주세요!

2021-09-02 02:40 UTC, ghojeong commented on xamarin/Calculator/Calculator/MainPage.xaml.cs
> +            MultiplyButton = new Button() { Text = "*" };
오 넵! 도전해보겠습니다!

2021-09-02 03:00 UTC, ghojeong reviewed
질문 하나 드립니다!

2021-09-02 07:09 UTC, nathankim0 commented on xamarin/Calculator/Calculator/MainPage.xaml.cs
> +        #endregion
Button 의  CommandPrameter에 각각 연산 기호를 넣어주거나, 해당 Text를 가져와서 하나의 함수로 사용할 수 있습니다.

```
 private void OnKeypadPressed(object sender, EventArgs e)
        {
            var numberOperation = ((ClickedEventArgs)e).Parameter as string;
            // 또는,  var numberOperation = (sender as Button).Text;

            switch (numberOperation)
            {
                case "+":
                    Result += NumberBuffer;
                    break;
                case "-":
                    Result -= NumberBuffer;
                    break;
                case "/":
                    Result /= NumberBuffer;
                    break;
                case "*":
                    Result *= NumberBuffer;
                    break;
            }

            NumberBuffer = 0;
        } 
```

이렇게 해보는 건 어떨까요? parameter를 사용할때는 EventArgs 타입과 null을 조심해야할 것 같습니다..

2021-09-02 07:46 UTC, ghojeong commented on xamarin/Calculator/Calculator/MainPage.xaml.cs
> +        private void Plus_Pressed(object sender, EventArgs e)
이런 컨벤션 알려주셔서 감사합니다!
열심히 배우겠습니다.

2021-09-02 10:45 UTC, ghojeong commented on xamarin/Calculator/Calculator/MainPage.xaml.cs
> +        }
> Button 의 CommandPrameter에 각각 연산 기호를 넣어주거나, 해당 Text를 가져와서 하나의 함수로 사용할 수 있습니다.
> 이렇게 해보는 건 어떨까요? parameter를 사용할때는 EventArgs 타입과 null을 조심해야할 것 같습니다..

제안 주신 내용을 제 스타일로 바꾸어보았습니다.
굉장히 제 스타일인지라 피드백 부탁드립니다. @nathankim0

2021-09-03 01:01 UTC, nathan9608 commented on xamarin/Calculator/Calculator/MainPage.xaml.cs
> +        }
와 이렇게도 사용할 수 있군요.. 덕분에 좋은 방식 배웠습니다 !

2021-09-03 01:03 UTC, merged